# inter = intersections between datasets
# preprocess = preprocessing the raw data
mode: "preprocess"

# used only in inter mode
intersection_mode:
  cell_lines: ["GM12878", "HelaS3", "HepG2", "K562"]
  import_path: "/app/data"
  export_path: "/app/data/intersected"
  save_results: True
  combinations_length: [2, 3, 4]

# used only in preprocessmode
preprocess:
  import_path: "/app/data"
  export_path: "/app/data/filtered"
  cell_lines: ["A549", "GM12878", "HepG2", "K562"]
